config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  # root route
  root 'payments#index'
  resources :payments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :amount, :numericality => {:only_integer => true}
  validates_presence_of :to_from
  validates_presence_of :date
  validates_presence_of :amount
  validates_presence_of :purpose
  validates_date :date,  on_or_before: :today
end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def search
    @search = params["search"]
    if @search.present?
      @to_from = @search["to_from"]
      @status = @search["status"]
      @payments = Payment.where("to_from ILIKE ? AND status ILIKE ?", "%#{@to_from}%", "%#{@status}%").order(id: :asc).paginate(page: params[:page], per_page: 10)

      @allCount = Payment.where("to_from ILIKE ? AND status ILIKE ?", "%#{@to_from}%", "%#{@status}%").count;
      @allSum = Payment.where("to_from ILIKE ? AND status ILIKE ?", "%#{@to_from}%", "%#{@status}%").sum(:amount);
      @allCreditCount = Payment.select("*").where("to_from ILIKE ? AND status = 'Credit' ", "%#{@to_from}%").count;
      @allCreditSum = Payment.select("*").where("to_from ILIKE ? AND status = 'Credit' ", "%#{@to_from}%").sum(:amount);
      @allDebitCount = Payment.select("*").where("to_from ILIKE ? AND status = 'Debit' ", "%#{@to_from}%").count;
      @allDebitSum = Payment.select("*").where("to_from ILIKE ? AND status = 'Debit' ", "%#{@to_from}%").sum(:amount);
    end
  end

  def index
    @payments = Payment.all.order(id: :asc).paginate(page: params[:page], per_page: 10)

    @allCount = Payment.all.count;
    @allSum = Payment.all.sum(:amount);
    @allCreditCount = Payment.all.where(:status => 'Credit').count;
    @allCreditSum = Payment.all.where(:status => 'Credit').sum(:amount);
    @allDebitCount = Payment.all.where(:status => 'Debit').count;
    @allDebitSum = Payment.all.where(:status => 'Debit').sum(:amount);

    search
  end

  def show
    @payment = Payment.find(params[:id])
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(params_payment)

    if @payment.save
        redirect_to payments_path
    else
        render 'new'
    end
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.find(params[:id])
      if @payment.update(params_payment)
        redirect_to payments_path
      else
        render 'edit'
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    redirect_to payments_path
  end

  private

  def params_payment
    params.require(:payment).permit(:date, :purpose, :to_from, :amount, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light header">
    <%= link_to payments_path, class: 'btn btn-info m-10' do %>
      <span>All Payments</span>
    <% end %>
   <%= link_to new_payment_path, class: 'btn btn-info m-10' do %>
      <span>Add Payment</span>
    <% end %>
    <div class="div-inline">
      <%= link_to destroy_admin_session_path, method: :delete, class: 'btn  bg-danger m-10' do %>
        <span>Logout</span>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountingManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_admin %>
      <%= render "layouts/header" %>
    <% end %>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/payments/_insertForm.html.erb
<%= form_for :payment, url: payments_path, html: {method: :post} do |form| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row pb-4">
    <div class="col">
      <%= form.label :date %>
      <%= form.date_field :date, class: 'form-control', max: Date.today %>
    </div>
    <div class="col">
      <%= form.label :purpose %>
      <%= form.text_field :purpose, class: 'form-control', placeholder: 'Purpose' %>
    </div>
  </div>
  <div class="row pb-4">
    <div class="col">
      <%= form.label :to_from %>
      <%= form.text_field :to_from, class: 'form-control', placeholder: 'Beneficiary' %>
    </div>
    <div class="col">
      <%= form.label :status %>
      <%= form.select(:status, ['Debit', 'Credit'], {}, { :class => 'form-control' }) %>
    </div>
    <div class="col">
      <%= form.label :amount %>
      <%= form.text_field :amount, class: 'form-control', placeholder: 'Amount' %>
    </div>
  </div>
  <%= form.submit class: 'btn btn-success', value: 'Add New' %>
<% end %>

app/views/payments/_searchForm.html.erb
<%= simple_form_for :search, url: payments_path, method: "GET", html: { class: 'form-inline' } do |f| %>
  <%= f.input :to_from, input_html: {value: "", placeholder: "Beneficiary Name", class: 'form-control mx-1'} %>
  <%= f.input :status, input_html: {value: "", placeholder: "Debit/Credit", class: 'form-control mx-1'} %>
  <%= f.submit "Search", class: "btn btn-primary" %>
  <%= link_to "Clear", payments_path, class: 'btn btn-warning ml-2' %>
<% end %>

app/views/payments/_updateForm.html.erb
<%= form_for :payment, url: payment_path, html: {method: :put} do |form| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row pb-4">
    <div class="col">
      <%= form.label :date %>
      <%= form.date_field :date, class: 'form-control' %>
    </div>
    <div class="col">
      <%= form.label :purpose %>
      <%= form.text_field :purpose, class: 'form-control', placeholder: 'Purpose' %>
    </div>
  </div>
  <div class="row pb-4">
    <div class="col">
      <%= form.label :to_from %>
      <%= form.text_field :to_from, class: 'form-control', placeholder: 'Beneficiary' %>
    </div>
    <div class="col">
      <%= form.label :status %>
      <%= form.select(:status, ['Debit', 'Credit'], {}, { :class => 'form-control' }) %>
    </div>
    <div class="col">
      <%= form.label :amount %>
      <%= form.text_field :amount, class: 'form-control', placeholder: 'Amount' %>
    </div>
  </div>
    <%= form.submit class: 'btn btn-success', value: 'Update Product' %>
    <%= link_to "Cancel", payments_path, :class=>'btn btn-warning' %>
<% end %>

app/views/payments/edit.html.erb
<div class="container">
  <h1 class="py-4">Edit Payment</h1>
  <%= render 'updateForm' %>
</div>

app/views/payments/index.html.erb
<div class="row py-4">
  <div class=" col-md-6 col-12">
    <h1>All Payments</h1>
  </div>
  <div class=" col-md-6 col-12">
    <%= render 'searchForm' %>
  </div>
</div>

<div class="row border-bottom pb-4">
  <div class="col-12 col-md-2">
    <div class="card text-white bg-primary mb-3">
        <div class="card-header">Total Payments <span class="float-right"><%= @allCount %></span></div>
        <div class="card-body">
            <h1 class="card-title"><%= @allSum %></h1>
        </div>
    </div>
  </div>
  <div class="col-12 col-md-2">
    <div class="card text-white bg-success mb-3">
        <div class="card-header">Total Credits <span class="float-right"><%= @allCreditCount %></span></div>
        <div class="card-body">
            <h1 class="card-title"><%= @allCreditSum %></h1>
        </div>
    </div>
  </div>
  <div class="col-12 col-md-2">
    <div class="card text-white bg-danger mb-3">
        <div class="card-header">Total Debits <span class="float-right"><%= @allDebitCount %></span></div>
        <div class="card-body">
            <h1 class="card-title"><%= @allDebitSum %></h1>
        </div>
    </div>
  </div>
  <div class="col-12 col-md-2">
    <div class="card text-white bg-secondary mb-3">
        <div class="card-header">Outstanding Amount</div>
        <div class="card-body">
            <h1 class="card-title"><%= @allCreditSum-@allDebitSum %></h1>
        </div>
    </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Purpose</th>
      <th scope="col">To/From</th>
      <th scope="col">Status</th>
      <th scope="col">Amount</th>
      <th scope="col">Created at</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <th scope="row"><%= payment.id %></th>
        <td><%= payment.date %></td>
        <td><%= payment.purpose %></td>
        <td><%= payment.to_from %></td>
        <td><%= payment.status %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.created_at %></td>
        <td>
            <%= link_to edit_payment_path(payment), class: 'btn btn-info' do %>
                <span>Edit</span>
            <% end %>
            <%= link_to payment_path(payment), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' do %>
                <span>Delete</span>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @payments %>

app/views/payments/new.html.erb
<div class="container">
  <h1 class="py-4">New Payment</h1>
  <%= render 'insertForm' %>
</div>